name: TKG Proton Experimental - Lina Unity Leak Patch - TKG Proton v3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v5
      - name: Compile
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo lib32-jack2
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          chown user -R /tmp
          export CARGO_HOME="$PWD"
          cd proton-tkg
          sed -i 's/uninstaller="false"/uninstaller="true"/' proton-tkg.cfg
          sed -i 's/autoinstall="false"/autoinstall="true"/' proton-tkg.cfg
          sed -i 's/build_gstreamer="false"/build_gstreamer="true"/' proton-tkg.cfg
          sed -i 's/lib32_gstreamer="false"/lib32_gstreamer="true"/' proton-tkg.cfg
          sed -i 's/wayland_driver="false"/wayland_driver="true"/' proton-tkg.cfg
          sed -i 's/_use_staging="true"/_use_staging="false"/' proton-tkg.cfg
          sed -i 's/amdags-proton.mypatch //' proton-tkg.cfg
          sed -i 's/_nosteamruntime="false"/_nosteamruntime="sniper"/' proton-tkg-profiles/advanced-customization.cfg
          sed -i 's/_sdl_joy_support="false"/_sdl_joy_support="true"/' proton-tkg-profiles/advanced-customization.cfg
          #sed -i 's/_proton_use_steamhelper="true"/_proton_use_steamhelper="false"/' proton-tkg-profiles/advanced-customization.cfg
          sed -i 's/_NOLIB32="false"/_NOLIB32="true"/' proton-tkg-profiles/advanced-customization.cfg
          sed -i 's/_no_container="false"/_no_container="true"/' proton-tkg.sh
          sed -i 's/_PROTON_NAME_ADDON=""/_PROTON_NAME_ADDON="lina-unity-leak-patch-tkg-proton-v3"/' proton-tkg-profiles/advanced-customization.cfg
          rm ../wine-tkg-git/wine-tkg-userpatches/lina-unity-leak.mypatch
          yes|./proton-tkg.sh
          cd built
          cd proton_tkg_e*
          patch < ../../../custom-proton/proton-tkg-warudo.diff
          cd ..
          tar -cvzf ../Proton-Experimental-Lina-Unity-Leak-Patch-TKG-Proton-v3.tar.gz ./
          cd ..
          sha512sum Proton-Experimental-Lina-Unity-Leak-Patch-TKG-Proton-v3.tar.gz > Proton-Experimental-Lina-Unity-Leak-Patch-TKG-Proton-v3.sha512sum
      - name: Archive tar gz
        uses: actions/upload-artifact@v4
        with:
          name: Proton-Experimental-Lina-Unity-Leak-Patch-TKG-Proton-v3
          path: proton-tkg/Proton-Experimental-Lina-Unity-Leak-Patch-TKG-Proton-v3.tar.gz
      - name: Archive tar sha512sum
        uses: actions/upload-artifact@v4
        with:
          name: Proton-Experimental-Lina-Unity-Leak-Patch-TKG-Proton-v3-sha512sum
          path: proton-tkg/Proton-Experimental-Lina-Unity-Leak-Patch-TKG-Proton-v3.sha512sum


  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v5
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: TKG Proton Experimental - Lina Unity Leak Patch - TKG Proton v3
          preserve_order: true
          files: |
            Proton-Experimental-Lina-Unity-Leak-Patch-TKG-Proton-v3/Proton-Experimental-Lina-Unity-Leak-Patch-TKG-Proton-v3.tar.gz
            Proton-Experimental-Lina-Unity-Leak-Patch-TKG-Proton-v3-sha512sum/Proton-Experimental-Lina-Unity-Leak-Patch-TKG-Proton-v3.sha512sum
            